name: spark-svdpp-env
channels:
  - defaults
  - anaconda
dependencies:
  - python=3.7.5
  - pylint=2.4.4
  - flake8=3.7.9
  - h5py=2.9.0
  - ipython=7.9.0
  - numpy=1.17.3
  - pandas=0.25.3
  - pip=19.3.1
  - scipy=1.3.1
  - pyarrow=0.13.0
  - pytest=5.3.0
  - psutil=5.6.5
  - prompt_toolkit=2.0.10
