[tool.black]
line-length = 110
target-version = ["py310"]
skip-string-normalization = true

[tool.mypy]
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
ignore_missing_imports = true

[tool.isort]
profile = "black"

[tool.pydocstyle]
convention = "numpy"
add-ignore = "D100,D101,D102,D103,D104,D107,D203,D213"
